<?php
$blockObj= $block->getLayout()->createBlock('Flavour\FusionShipping\Block\View');
$visible = $blockObj->canShowBlock();

$dpd_cutoff = $blockObj->getDpdCutOff();
$royalmail_cutoff = $blockObj->getRoyalMailCutOff();

?>

<style>
    .bold-time {
        font-weight:800;
    }
</style>

<script>

    require([ 'jquery', 'jquery/ui'], function($){ $(document).ready(function($) {

        Date.prototype.addHours = function (h) {
            this.setHours(this.getHours() + h);
            return this;
        };

        var now = new Date();
        var royalmail = new Date(
            now.getFullYear(),
            now.getMonth(),
            now.getDate(),
            15,
            30,
            0,
            0
        );
        var dpd = new Date(
            now.getFullYear(),
            now.getMonth(),
            now.getDate(),
            18,
            30,
            0,
            0
        );

        var php_royalmail = "<?php echo $royalmail_cutoff; ?>";
        var php_dpd = "<?php echo $dpd_cutoff; ?>";

        var carrier1 = "royalmail";
        var carrier2 = "dpd";

        if (carrier1 === "royalmail") {
            var selected_carrier = royalmail;
            var selectedCarrier = selected_carrier;

            var selectedCarrier_name = carrier1;
            var dateFuture = selectedCarrier;
            var dateNow = new Date();

            var seconds = Math.floor((dateFuture - dateNow) / 1000);
            var minutes = Math.floor(seconds / 60);
            var hours = Math.floor(minutes / 60);
            var days = Math.floor(hours / 24);

            hours = hours - days * 24;
            minutes = minutes - days * 24 * 60 - hours * 60;

            document.getElementById("custom_royalmail").innerHTML = "<span class='bold-time'>" + hours + "h:" + minutes + "m </span>" + "to place a " + selectedCarrier_name + " order ";
            // document.getElementById("custom_php_royalmail").innerHTML = php_royalmail;
            // document.getElementById("royalmail").innerHTML = royalmail;

        }

        if (carrier2 === "dpd") {
            var selected_carrier = dpd;
            var selectedCarrier = selected_carrier;

            var selectedCarrier_name = carrier2;
            var dateFuture = selectedCarrier;
            var dateNow = new Date();

            var seconds = Math.floor((dateFuture - dateNow) / 1000);
            var minutes = Math.floor(seconds / 60);
            var hours = Math.floor(minutes / 60);
            var days = Math.floor(hours / 24);

            hours = hours - days * 24;
            minutes = minutes - days * 24 * 60 - hours * 60;

            document.getElementById("custom_dpd").innerHTML = "<span class='bold-time'>" + hours + "h:" + minutes + "m </span>" + "to place a " + selectedCarrier_name + " order ";
            // document.getElementById("custom_php_dpd").innerHTML = php_dpd;
            // document.getElementById("dpd").innerHTML = dpd;

        }

    });
    });
</script>

<h5 class="timer-text">Order Now for Next day Delivery!</h5>

<?php if ($visible) { ?>
    <div>
<!--        <p>There is</p>-->
        <p id="custom_royalmail"></p>
        <p id="custom_dpd"></p>
    </div>

    <div>
<!--        <p>Admin set variables</p>-->
        <p id="custom_php_royalmail"></p>
        <p id="custom_php_dpd"></p>
    </div>

    <div>
<!--        <p>Live Javascript rendered dates</p>-->
        <p id="royalmail"></p>
        <p id="dpd"></p>
    </div>
<?php } else { ?>
    <?= "i'm not visible"; ?>
    <p>Custom Delivery Information unavailable</p>
<?php } ?>