<?php
$blockObj= $block->getLayout()->createBlock('Flavour\FusionShipping\Block\View');
$visible = $blockObj->canShowBlock();
?>

<?php if ($visible) { ?>
    <h5>Royal Mail Tracked 24 Hour</h5>
    <p>Royal Mail Tracked 24 has an estimated delivery time of between 1-2 working
        days and only applies to orders placed before 3.00pm Monday-Friday
        (excluding public holidays) Orders placed after this time will be despatched
        on the next working day. Customers living in remote locations may experience
        slightly longer delivery times.</p>
    <p>Orders placed on the Friday will still be delivered Saturday</p>

    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.</p>

    <h5>Royal Mail Tracked 48 Hour</h5>
    <p>Royal Mail Tracked 48 has an estimated delivery time of between 2-3 working
        days and only applies to orders placed before 3.00pm Monday-Friday
        (excluding public holidays) Orders placed after this time will be despatched
        on the next working day. Customers living in remote locations may experience
        slightly longer delivery times.</p>

    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.</p>

    <h5>Royal Mail First Class Postage – Free</h5>
    <p>Royal Mail First Class post no signature required is an economy postal
        service with an estimated delivery time of between 1-3 working days and only
        applies to orders placed before 3.00pm Monday-Friday (excluding public
        holidays) Orders placed after this time will be despatched on the next
        working day. Customers living in remote locations may experience slightly
        longer delivery times.</p>

    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.</p>

    <h5>DPD - International</h5>
    <p>Estimated Delivery to your destination is between 2-3 working days. This is a
        tracked service.</p>

    <h5>DPD Saturday Delivery</h5>
    <p>Saturday delivery only applies to orders placed before 6:30pm on Friday. This
        is a fully tracked service.</p>

    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.</p>

    <p>Please note this delivery option is not available
        for customers in Guernsey,
        Jersey, Northern Ireland, Scottish highlands or Aberdeenshire.</p>

    <h5>Free Shipping over £20</h5>
    <p>Orders over £20 will receive free Royal Mail tracked delivery service and
        will require a signature. Please allow 2 to 3 working days for delivery after
        dispatch.</p>

    <h5>First Class Postage – Free</h5>
    <p>Free delivery without tracking (no signature required) is only available on
        10ml
        e-liquid orders placed with a maximum of 12 bottles per order with
        Royal Mail’s first class delivery service. Please allow 1 to 3
        working days for delivery after dispatch.</p>

    <h5>DPD Next Working Day</h5>
    <p>Next day delivery only applies to orders placed before 6:30pm Monday-Friday,
        orders placed after this time will be despatched the next working day.
        This is a fully tracked service. Orders placed on a Friday will not be
        delivered on a Saturday using this service.</p>

    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.
    </p>

    <p>
        Please note this delivery option is not available
        for customers in Guernsey,
        Jersey, Northern Ireland, Scottish highlands or Aberdeenshire.
    </p>

    <p>below is an example of getting this shipping methods from the block function</p>

<?php } else { ?>
    <?= "i'm not visible"; ?>
    <p>Delivery Information unavailable</p>
<?php } ?>



<?php

//$order = $block->getOrderItems();
//$orderItems = $order->getAllItems();
//$code = $orderItems->getShippingMethod();

//echo 'order' . $code;
//$order->getShippingMethod();

?>


<?php //$carriers = $block->getShippingMethods(); ?>
<!--<select name="shipping"  class="control-select">-->
<!--    <option value="">--><?php ///* @escapeNotVerified */ echo __('Please Select'); ?><!--</option>-->
<!--    --><?php //foreach ($carriers as $carrier): ?>
<!--        <optgroup label="--><?php ///* @escapeNotVerified */ echo $carrier['label'] ?><!--">-->
<!--            --><?php //foreach ($carrier['value'] as $child): ?>
<!--                <option value="--><?php ///* @escapeNotVerified */ echo $child['value'] ?><!--">-->
<!--                    --><?php ///* @escapeNotVerified */ echo $child['label']; ?>
<!--                </option>-->
<!--            --><?php //endforeach; ?>
<!--        </optgroup>-->
<!--    --><?php //endforeach; ?>
<!--</select>-->
